# This code is a Qiskit project.
#
# (C) Copyright IBM 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""A subprocess-based wrapper for the SBD diagonalization solver."""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from collections.abc import Sequence
from pathlib import Path

import numpy as np
from pyscf import tools

from qiskit_addon_sqd.fermion import SCIResult, SCIState


class SBDExecutionError(Exception):
    """Custom exception for SBD command line application execution errors."""

    def __init__(self, command, returncode, log_path):
        """Initialize a ``SBDExecutionError`` instance."""
        self.command = command
        self.returncode = returncode
        self.log_path = log_path

        message = (
            f"Command '{command}' failed with return code {returncode}\n"
            f"See the log file at {log_path} for more details."
        )
        super().__init__(message)


def solve_sci(
    ci_strings: tuple[np.ndarray, np.ndarray],
    one_body_tensor: np.ndarray,
    two_body_tensor: np.ndarray,
    norb: int,
    nelec: tuple[int, int],
    *,
    spin_sq: float | None = None,
    sbd_path: str | Path | None = None,
    mpirun_options: Sequence[str] | str | None = None,
    sbd_config: dict | None = None,
    temp_dir: str | Path | None = None,
    clean_temp_dir: bool = True,
) -> SCIResult:
    """Diagonalize Hamiltonian in subspace defined by CI strings using SBD executable.

    Args:
        ci_strings: Pair (strings_a, strings_b) of arrays of spin-alpha CI
            strings and spin-beta CI strings whose Cartesian product give the basis of
            the subspace in which to perform a diagonalization.
        one_body_tensor: The one-body tensor of the Hamiltonian.
        two_body_tensor: The two-body tensor of the Hamiltonian.
        norb: The number of spatial orbitals.
        nelec: The numbers of alpha and beta electrons.
        spin_sq: Target value for the total spin squared (currently unused by SBD).
        sbd_path: Path to the SBD executable. If None, looks for 'sbd_diag' in PATH.
        mpirun_options: Options controlling the CPU resource allocation for the SBD executable.
            These command-line options will be passed directly to the ``mpirun`` command line application.
            These may be formatted as a ``Sequence`` of strings or a single string. If a ``Sequence``,
            the elements will be combined into a single, space-delimited string and passed to
            ``mpirun``. If the input is a single string, it will be passed to ``mpirun`` as-is. If no
            ``mpirun_options`` are provided by the user, SBD will run on a single MPI slot.
        sbd_config: Dictionary of SBD configuration parameters (method, max_it, tolerance, etc.).
        temp_dir: An absolute path to a directory for storing temporary files. If not provided, the
            system temporary files directory will be used.
        clean_temp_dir: Whether to delete intermediate files generated by the SBD executable.
            These files will be stored in a directory created inside ``temp_dir``. If ``False``, then
            this directory will be preserved.

    Returns:
        The diagonalization result.
    """
    import time
    
    n_alpha, n_beta = nelec

    # Set up the temp directory
    temp_dir = temp_dir or tempfile.gettempdir()
    sbd_dir = Path(tempfile.mkdtemp(prefix="sbd_cli_files_", dir=temp_dir))

    try:
        # === TIMING: Setup phase ===
        t_setup_start = time.time()
        
        # Write the integrals out as an FCI dump for SBD
        fcidump_path = sbd_dir / "fcidump.txt"
        tools.fcidump.from_integrals(fcidump_path, one_body_tensor, two_body_tensor, norb, nelec)

        # Write determinant files
        _write_determinant_files(ci_strings, sbd_dir, norb)

        # Set up carryover output files
        carryover_adet_file = sbd_dir / "carryover_alpha.txt"
        carryover_bdet_file = sbd_dir / "carryover_beta.txt"

        # Set up wavefunction dump file
        # Use .bin extension to trigger SBD's fast binary write path
        # (SaveMatrixFormWF in restart.h checks extension: .bin → raw doubles, .txt → slow text)
        wf_dump_file = sbd_dir / "wavefunction.bin"
        
        t_setup_end = time.time()
        print(f"[SBD Timing] Setup (write files): {t_setup_end - t_setup_start:.4f} sec")

        # === TIMING: SBD solver execution ===
        t_sbd_start = time.time()
        
        # Call SBD executable
        _call_sbd(
            sbd_dir,
            sbd_path=sbd_path,
            mpirun_options=mpirun_options,
            sbd_config=sbd_config,
            carryover_adet_file=carryover_adet_file,
            carryover_bdet_file=carryover_bdet_file,
            wf_dump_file=wf_dump_file,
        )
        
        t_sbd_end = time.time()
        print(f"[SBD Timing] SBD solver execution: {t_sbd_end - t_sbd_start:.4f} sec")

        # === TIMING: Read outputs ===
        t_read_start = time.time()
        
        # Read and convert outputs
        energy, sci_state, occupancies = _read_sbd_outputs(
            sbd_dir, norb, nelec, carryover_adet_file, carryover_bdet_file, wf_dump_file
        )
        
        t_read_end = time.time()
        print(f"[SBD Timing] Read outputs: {t_read_end - t_read_start:.4f} sec")
        print(f"[SBD Timing] Total: {t_read_end - t_setup_start:.4f} sec")

        return SCIResult(energy, sci_state, orbital_occupancies=occupancies)

    finally:
        # Clean up the temp directory of intermediate files, if desired
        if clean_temp_dir:
            shutil.rmtree(sbd_dir, ignore_errors=True)


def solve_sci_batch(
    ci_strings: list[tuple[np.ndarray, np.ndarray]],
    one_body_tensor: np.ndarray,
    two_body_tensor: np.ndarray,
    norb: int,
    nelec: tuple[int, int],
    *,
    spin_sq: float | None = None,
    sbd_path: str | Path | None = None,
    mpirun_options: Sequence[str] | str | None = None,
    sbd_config: dict | None = None,
    temp_dir: str | Path | None = None,
    clean_temp_dir: bool = True,
) -> list[SCIResult]:
    """Diagonalize Hamiltonian in multiple subspaces using SBD executable.

    Args:
        ci_strings: List of pairs (strings_a, strings_b) of arrays of spin-alpha CI
            strings and spin-beta CI strings whose Cartesian product give the basis of
            the subspace in which to perform a diagonalization.
        one_body_tensor: The one-body tensor of the Hamiltonian.
        two_body_tensor: The two-body tensor of the Hamiltonian.
        norb: The number of spatial orbitals.
        nelec: The numbers of alpha and beta electrons.
        spin_sq: Target value for the total spin squared (currently unused by SBD).
        sbd_path: Path to the SBD executable. If None, looks for 'sbd_diag' in PATH.
        mpirun_options: Options controlling the CPU resource allocation for the SBD executable.
        sbd_config: Dictionary of SBD configuration parameters.
        temp_dir: An absolute path to a directory for storing temporary files.
        clean_temp_dir: Whether to delete intermediate files.

    Returns:
        The results of the diagonalizations in the subspaces given by ci_strings.
    """
    return [
        solve_sci(
            ci_strs,
            one_body_tensor,
            two_body_tensor,
            norb=norb,
            nelec=nelec,
            spin_sq=spin_sq,
            sbd_path=sbd_path,
            mpirun_options=mpirun_options,
            sbd_config=sbd_config,
            temp_dir=temp_dir,
            clean_temp_dir=clean_temp_dir,
        )
        for ci_strs in ci_strings
    ]


def _write_determinant_files(
    ci_strings: tuple[np.ndarray, np.ndarray],
    sbd_dir: Path,
    norb: int,
) -> None:
    """Write determinant files in SBD format (binary strings)."""
    strings_a, strings_b = ci_strings

    # Write alpha determinants
    adet_path = sbd_dir / "alphadets.txt"
    with open(adet_path, "w") as f:
        for ci_str in strings_a:
            # Convert integer to binary string (right-to-left ordering)
            binary_str = format(int(ci_str), f"0{norb}b")
            f.write(binary_str + "\n")

    # Write beta determinants
    bdet_path = sbd_dir / "betadets.txt"
    with open(bdet_path, "w") as f:
        for ci_str in strings_b:
            binary_str = format(int(ci_str), f"0{norb}b")
            f.write(binary_str + "\n")


def _call_sbd(
    sbd_dir: Path,
    sbd_path: str | Path | None,
    mpirun_options: Sequence[str] | str | None,
    sbd_config: dict | None,
    carryover_adet_file: Path,
    carryover_bdet_file: Path,
    wf_dump_file: Path,
) -> None:
    """Navigate to the SBD dir, invoke SBD executable, and check for success."""
    # Locate SBD executable
    if sbd_path is None:
        sbd_executable = shutil.which("sbd_diag")
        if sbd_executable is None:
            raise FileNotFoundError(
                "SBD executable 'sbd_diag' not found in PATH. "
                "Please provide the path via the sbd_path parameter or add it to PATH."
            )
    else:
        sbd_executable = str(sbd_path)
        if not os.path.exists(sbd_executable):
            raise FileNotFoundError(f"SBD executable not found at: {sbd_executable}")

    # Build command line arguments
    sbd_args = [
        "--fcidump", "fcidump.txt",
        "--adetfile", "alphadets.txt",
        "--bdetfile", "betadets.txt",
        "--carryover_adetfile", str(carryover_adet_file.name),
        "--carryover_bdetfile", str(carryover_bdet_file.name),
        "--dump_matrix_form_wf", str(wf_dump_file.name),
    ]

    # Add configuration parameters
    config = sbd_config or {}
    
    # Default configuration
    method = config.get("method", 0)  # 0=Davidson
    max_it = config.get("max_it", 100)
    max_nb = config.get("max_nb", 50)
    tolerance = config.get("tolerance", 1e-8)
    carryover_type = config.get("carryover_type", 1)
    carryover_ratio = config.get("carryover_ratio", 0.1)
    carryover_threshold = config.get("carryover_threshold", 1e-4)
    bit_length = config.get("bit_length", 64)
    do_rdm = config.get("do_rdm", 1)  # Changed default to 1 for full RDM
    
    # MPI communicator sizes
    task_comm_size = config.get("task_comm_size", 1)
    adet_comm_size = config.get("adet_comm_size", 1)
    bdet_comm_size = config.get("bdet_comm_size", 1)

    sbd_args.extend([
        "--method", str(method),
        "--iteration", str(max_it),
        "--block", str(max_nb),
        "--tolerance", str(tolerance),
        "--carryover_type", str(carryover_type),
        "--carryover_ratio", str(carryover_ratio),
        "--carryover_threshold", str(carryover_threshold),
        "--bit_length", str(bit_length),
        "--rdm", str(do_rdm),
        "--task_comm_size", str(task_comm_size),
        "--adet_comm_size", str(adet_comm_size),
        "--bdet_comm_size", str(bdet_comm_size),
    ])

    # Build MPI command
    if mpirun_options:
        if isinstance(mpirun_options, str):
            mpirun_options = mpirun_options.split()
        sbd_call = ["mpirun"] + list(mpirun_options) + [sbd_executable] + sbd_args
    else:
        sbd_call = ["mpirun", sbd_executable] + sbd_args

    # Execute SBD
    sbd_log_path = sbd_dir / "sbd_solver_logfile.log"
    with open(sbd_log_path, "w") as logfile:
        process = subprocess.run(
            sbd_call, cwd=sbd_dir, stdout=logfile, stderr=logfile
        )

    # Check for successful execution by verifying output files exist
    if not carryover_adet_file.exists():
        raise SBDExecutionError(
            command=" ".join(sbd_call),
            returncode=process.returncode,
            log_path=sbd_log_path,
        )


def _read_sbd_outputs(
    sbd_dir: Path,
    norb: int,
    nelec: tuple[int, int],
    carryover_adet_file: Path,
    carryover_bdet_file: Path,
    wf_dump_file: Path,
) -> tuple[float, SCIState, tuple[np.ndarray, np.ndarray]]:
    """Read SBD output files and construct SCIResult."""
    # Read energy from log file (SBD prints it to stdout)
    log_path = sbd_dir / "sbd_solver_logfile.log"
    energy = None
    with open(log_path, "r") as f:
        for line in f:
            # Look for "Energy = " pattern in SBD output
            if "Energy =" in line:
                parts = line.split("=")
                if len(parts) >= 2:
                    try:
                        energy = float(parts[1].strip())
                        break
                    except ValueError:
                        continue

    if energy is None:
        raise ValueError(f"Could not extract energy from SBD log file: {log_path}")

    # Read occupancies from 1pRDM.txt file (diagonal elements of density matrix)
    # The 1pRDM.txt format is: i j value (sparse format)
    # Diagonal elements (i==j) give the orbital occupancies
    rdm_file = sbd_dir / "1pRDM.txt"
    occupancies_a = np.zeros(norb)
    occupancies_b = np.zeros(norb)
    
    if rdm_file.exists():
        try:
            with open(rdm_file, "r") as f:
                for line in f:
                    parts = line.strip().split()
                    if len(parts) == 3:
                        i, j, value = int(parts[0]), int(parts[1]), float(parts[2])
                        # Diagonal elements are occupancies
                        if i == j and i < norb:
                            # SBD stores spin-up and spin-down in same matrix
                            # For closed-shell, both spins have same occupancy
                            occupancies_a[i] = value
                            occupancies_b[i] = value
        except (IOError, ValueError) as e:
            # If reading fails, fall back to zeros
            pass
    
    occupancies = (occupancies_a, occupancies_b)

    # Read input determinants (full set used for diagonalization)
    input_strings_a = _read_determinant_file(sbd_dir / "alphadets.txt", norb)
    input_strings_b = _read_determinant_file(sbd_dir / "betadets.txt", norb)
    
    # Read carryover determinants (subset selected by SBD)
    co_strings_a = _read_determinant_file(carryover_adet_file, norb)
    co_strings_b = _read_determinant_file(carryover_bdet_file, norb)

    # Read wavefunction coefficients - required for SBD
    if not wf_dump_file.exists():
        raise FileNotFoundError(
            f"Wavefunction file not found: {wf_dump_file}. "
            "SBD should have written this file during diagonalization."
        )
    
    # SBD writes the full wavefunction for all input determinants
    # We need to extract only the carryover subset
    full_amplitudes = _read_wavefunction_file(
        wf_dump_file, len(input_strings_a), len(input_strings_b)
    )
    
    if full_amplitudes is None:
        raise ValueError(
            f"Failed to read wavefunction from {wf_dump_file}. "
            f"Expected {len(input_strings_a)} x {len(input_strings_b)} coefficients."
        )
    
    # Extract carryover subset by finding indices of carryover dets in input dets
    amplitudes = _extract_carryover_amplitudes(
        full_amplitudes, input_strings_a, input_strings_b, co_strings_a, co_strings_b
    )

    # Create SCIState
    sci_state = SCIState(
        amplitudes=amplitudes,
        ci_strs_a=co_strings_a,
        ci_strs_b=co_strings_b,
        norb=norb,
        nelec=nelec,
    )

    return energy, sci_state, occupancies


def _read_determinant_file(filepath: Path, norb: int) -> np.ndarray:
    """Read determinant file and convert binary strings to integers."""
    if not filepath.exists():
        return np.array([], dtype=np.int64)

    ci_strings = []
    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                # Convert binary string to integer
                ci_str = int(line, 2)
                ci_strings.append(ci_str)

    return np.array(ci_strings, dtype=np.int64)


def _extract_carryover_amplitudes(
    full_amplitudes: np.ndarray,
    input_strings_a: np.ndarray,
    input_strings_b: np.ndarray,
    co_strings_a: np.ndarray,
    co_strings_b: np.ndarray,
) -> np.ndarray:
    """Extract carryover subset from full wavefunction matrix.
    
    Args:
        full_amplitudes: Full wavefunction matrix (n_input_a x n_input_b)
        input_strings_a: All input alpha determinants
        input_strings_b: All input beta determinants
        co_strings_a: Carryover alpha determinants (subset)
        co_strings_b: Carryover beta determinants (subset)
    
    Returns:
        Carryover amplitudes matrix (n_co_a x n_co_b)
    """
    # Create mapping from determinant to index
    input_map_a = {det: i for i, det in enumerate(input_strings_a)}
    input_map_b = {det: i for i, det in enumerate(input_strings_b)}
    
    # Find indices of carryover dets in input dets
    co_indices_a = [input_map_a[det] for det in co_strings_a]
    co_indices_b = [input_map_b[det] for det in co_strings_b]
    
    # Extract subset using advanced indexing
    return full_amplitudes[np.ix_(co_indices_a, co_indices_b)]


def _read_wavefunction_file(
    filepath: Path, n_alpha: int, n_beta: int
) -> np.ndarray | None:
    """Read wavefunction coefficients from SBD binary output file.
    
    The .bin file contains raw float64 values in row-major (n_alpha x n_beta) order.
    This is much faster than parsing the text format.
    """
    try:
        if not filepath.exists():
            return None
        
        # Fast binary read: raw float64 values in row-major order
        flat = np.fromfile(str(filepath), dtype=np.float64)
        
        # Verify size matches expected dimensions
        if flat.size == n_alpha * n_beta:
            return flat.reshape(n_alpha, n_beta)
        else:
            # Size mismatch, return None
            return None
            
    except (FileNotFoundError, IOError, ValueError):
        return None

# Made with Bob
